### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by lrtoper** [CodeXTF2/PyHmmm#2]
python3 ./handler.py
stone@ubuntu:~/vscode/PyHmmm$ python3 ./handler.py
Traceback (most recent call last):
  File "./handler.py", line 3, in <module>
    from havoc.service import HavocService
  File "/home/stone/vscode/PyHmmm/havoc/service.py", line 133
    match data[ "Head" ][ "Type" ]:
          ^
SyntaxError: invalid syntax

**Comment by CodeXTF2** [comment]
Thats a havoc-py issue not mine.
